account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path("register/", views.register_view, name="register-view"),
    path("login/", views.login_view, name="login-view"),
    path("logout/", views.logout_view, name="logout-view"),
    path("profile/", views.profile_view, name="profile-view"),
]

core/urls.py
from django.views.generic import TemplateView
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path("", views.index_view, name="index-view"),
    path("integration/", views.integration_view, name="integration-view"),
    path("integration/add", views.integration_add_view, name="integration-add-view"),
    path("integration/update/<int:integration_id>", views.integration_update, name="integration-update"),
    path("integration/delete/<int:integration_id>", views.integration_delete, name="integration-delete"),
    path(
        "integration/update_products/<int:integration_id>",
        views.integration_update_products,
        name="integration-update-products"
    ),
    path("integration/export/<int:integration_id>", views.export_to_file, name="export_to_file"),
    path("integration/import/<int:integration_id>", views.import_from_file, name="import_from_file"),
    path("product/update/<int:product_id>", views.update_product, name="update-product"),
    path("products/", views.products_view, name="products-view"),
    path("products/<int:integration_id>", views.products_view, name="integration-products-view"),
    path("bot_setting/update/<int:bot_id>", views.update_bot_setting, name="update-bot-setting"),
    path("bot_setting/update-all/", views.update_all_bot_setting, name="update-all-bot-setting"),
    path("staff/", views.staff_view, name="staff-view"),
    path("get_products_for_parsing/", views.get_products_for_parsing, name="get-products-for-parsing"),
    path("parse_from_client/", views.parse_from_client, name="parse-from-client"),
    path("parse_client/", TemplateView.as_view(template_name='core/parser.html'), name="parse-client"),
    path("save_bot_ip_address", views.save_bot_ip_address, name="save-bot-ip-address"),
]

kaspi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('', include('core.urls')),
    path('account/', include('account.urls')),
    path('secret_admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12)

    def __str__(self) -> str:
        return f'{self.user.first_name} in {self.company.first()}'


class Company(models.Model):
    employees = models.ManyToManyField(Employee, related_name='company')
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Employee.objects.create(user=instance)
    instance.employee.save()

core/models.py
from django.db import models


class Integration(models.Model):
    company = models.ForeignKey(
        'account.Company',
        on_delete=models.CASCADE,
        related_name='integrations'
    )
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    api_token = models.CharField(max_length=500)
    partner_id = models.CharField(max_length=100, null=True)
    shop_name = models.CharField(max_length=100)
    launch_interval = models.IntegerField(default=20)
    status = models.BooleanField(default=False)
    last_update = models.DateTimeField(auto_now=True)
    is_xml_link_set = models.BooleanField(default=False)
    in_parsing_process = models.BooleanField(default=False)
    parsing_progress = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    admin_enabled = models.BooleanField(default=True)
    auth_cookie = models.CharField(max_length=500, null=True)

    def disable_all_bot_settings(self):
        for product_in_integration in self.products_in_integration.prefetch_related('bot_settings').all():
            bot_settings = product_in_integration.bot_settings.all()
            for bot_setting in bot_settings:
                bot_setting.active = False
            BotSetting.objects.bulk_update(bot_settings, ['active'], batch_size=500)

    def __str__(self):
        return self.shop_name


class Product(models.Model):
    name = models.CharField(max_length=250, null=True, blank=True)
    last_category = models.CharField(max_length=250, null=True)
    brand = models.CharField(max_length=250, null=True)
    kaspi_code = models.CharField(max_length=250)
    kaspi_url = models.URLField(null=True)
    image_url = models.URLField(null=True)

    def __str__(self):
        return str(self.name)


class City(models.Model):
    name = models.CharField(max_length=100)
    id_in_kaspi = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class PickupPoint(models.Model):
    name = models.CharField(max_length=50)
    available = models.BooleanField(default=False)
    integration = models.ForeignKey(
        Integration,
        on_delete=models.CASCADE,
        related_name='pickup_points'
    )
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)


class ProductInIntegration(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    integration = models.ForeignKey(
        Integration,
        models.CASCADE,
        related_name='products_in_integration'
    )
    sku = models.CharField(max_length=250, null=True)

    def __str__(self):
        return str(self.product.name)

    @property
    def is_current_price_exist(self):
        for bot_setting in self.bot_settings.all():
            if bot_setting.current_price:
                return True

        return False

    @property
    def is_any_active(self):
        for bot_setting in self.bot_settings.all():
            if bot_setting.active:
                return True

        return False


class BotSetting(models.Model):
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    product_in_integration = models.ForeignKey(
        ProductInIntegration,
        on_delete=models.CASCADE,
        related_name='bot_settings'
    )
    current_place_in_city = models.IntegerField(null=True)
    first_place_price = models.IntegerField(null=True)
    second_place_price = models.IntegerField(null=True)
    last_place_price = models.IntegerField(null=True)
    current_price = models.IntegerField(null=True)
    min_price = models.IntegerField(null=True)
    max_price = models.IntegerField(null=True)
    step = models.IntegerField(default=1)
    active = models.BooleanField(default=False)
    last_update = models.DateTimeField(null=True)
    pickup_points = models.JSONField(null=True)
    last_price_update = models.IntegerField(null=True)

    def __str__(self):
        return f'{self.product_in_integration.product.name} in {self.city.name}'

    class Meta:
        ordering = ['city__name', 'active']


class Worker(models.Model):
    timestamp = models.DateTimeField(auto_now=True)


class BotIpAddress(models.Model):
    ip = models.CharField(max_length=100)

    def __str__(self):
        return str(self.ip)

core/views.py
import json
import threading
from datetime import timedelta

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from .file_operations import (
    get_parsed_products_count,
    save_parsed_products_count
)
from .models import Integration, BotSetting, ProductInIntegration, City, Product, Worker, BotIpAddress
from .parser import (
    get_company_name,
    import_products_from_file
)
from .xlsx_generator import generate_xlsx
from .xml_generator import generate_xml
from account.models import Employee
from .tasks import update_bot_settings, add_data_to_db_from_parser, get_all_products_from_company

PARSED_PRODUCTS = 0


@login_required(login_url='/account/login/')
def index_view(request):
    if not request.user.is_authenticated:
        return redirect('account:login-view')

    workers = Worker.objects.filter(
        timestamp__gt=timezone.now() - timedelta(minutes=15)
    )
    active_workers_count = workers.count() * 2
    products_count = Product.objects.all().count()
    employee_list = Employee.objects.all().exclude(pk=2).order_by('pk')
    context = {
        'active_workers_count': active_workers_count,
        'products_count': products_count,
        'employee_list': employee_list
    }
    return render(request, 'core/index.html', context)


@login_required(login_url='/account/login/')
def staff_view(request):
    return render(request, 'core/staff.html', {})


@login_required(login_url='/account/login/')
def integration_view(request):
    return render(request, 'core/integrations.html', {})


@login_required(login_url='/account/login/')
def integration_add_view(request):
    if request.method == 'POST':
        integration = Integration.objects.create(
            company=request.user.employee.company.all().first(),
            username=request.POST.get('username'),
            password=request.POST.get('password'),
            api_token=request.POST.get('token'),
        )
        shop_name = get_company_name(integration)
        integration.shop_name = shop_name[0]
        integration.partner_id = shop_name[1]
        integration.save()
        get_all_products_from_company(integration.id)
        p = threading.Thread(target=get_all_products_from_company, args=(integration.id,))
        p.start()
        return redirect('core:integration-view')
    return render(request, 'core/add_integration.html', {})


@login_required(login_url='/account/login/')
def integration_update(request, integration_id):
    integration = Integration.objects.get(pk=integration_id)
    interval = request.GET.get("interval", '')
    status = request.GET.get("status", '')
    if interval != '':
        integration.launch_interval = int(interval)
        integration.save()
        return JsonResponse({"success": True})
    elif status != '':
        integration.status = True if status == 'true' else False
        integration.save()
        return JsonResponse({"success": True})
    return JsonResponse({"success": False})


@login_required(login_url='/account/login/')
def integration_delete(request, integration_id):
    integration = Integration.objects.get(pk=integration_id)
    integration.delete()
    return redirect('core:integration-view')


@login_required(login_url='/account/login/')
def integration_update_products(request, integration_id):
    p = threading.Thread(target=get_all_products_from_company, args=(integration_id,))
    p.start()
    return redirect('core:integration-view')


@login_required(login_url='/account/login/')
def products_view(request, integration_id=0):
    integration = None
    if integration_id == 0:
        try:
            integration = Integration.objects.filter(company=request.user.employee.company.all().first()).first()
        except:
            redirect('core:integration-view')
    else:
        integration = Integration.objects.get(pk=integration_id)
    if not integration:
        return redirect('core:integration-view')
    page_number = request.GET.get("page", 1)
    search_query = request.GET.get("search", '')
    city_query = request.GET.get("city_ids", '')
    brand_query = request.GET.get("brands", '')
    min_price = request.GET.get("min_price", False)
    max_price = request.GET.get("max_price", False)
    not_min_price = request.GET.get("not_min_price", False)
    not_max_price = request.GET.get("not_max_price", False)
    city_ids = []
    brand_list = []
    if city_query:
        city_ids = city_query.split(';')
    if brand_query:
        brand_list = brand_query.split(';')
    if min_price == 'true':
        min_price = True
    if not_min_price == 'true':
        not_min_price = True
    if max_price == 'true':
        max_price = True
    if not_max_price == 'true':
        not_max_price = True
    if brand_list and not city_ids:
        products = ProductInIntegration.objects.prefetch_related(
            'product',
            'bot_settings',
            'bot_settings__city'
        ).filter(
            integration__id=integration.pk,
            bot_settings__active=True,
            product__brand__in=brand_list
        ).distinct().order_by('pk')
    elif brand_list and city_ids:
        products = ProductInIntegration.objects.prefetch_related(
            'product',
            'bot_settings',
            'bot_settings__city'
        ).filter(
            integration__id=integration.pk,
            bot_settings__active=True,
            product__brand__in=brand_list,
            bot_settings__city__id_in_kaspi__in=city_ids
        ).distinct().order_by('pk')
    elif not brand_list and city_ids:
        products = ProductInIntegration.objects.prefetch_related(
            'product',
            'bot_settings',
            'bot_settings__city'
        ).filter(
            integration__id=integration.pk,
            bot_settings__active=True,
            bot_settings__city__id_in_kaspi__in=city_ids
        ).distinct().order_by('pk')
    else:
        products = ProductInIntegration.objects.prefetch_related(
            'product',
            'bot_settings',
            'bot_settings__city'
        ).filter(
            integration__id=integration.pk,
            bot_settings__active=True
        ).distinct().order_by('pk')
    if search_query != '':
        products = products.filter(
            Q(product__name__icontains=search_query) |
            Q(product__brand__icontains=search_query) |
            Q(product__kaspi_code__icontains=search_query) |
            Q(sku__icontains=search_query)
        )

    if min_price and not not_min_price and not max_price and not not_max_price:
        products = products.filter(bot_settings__min_price__gt=0)
    if not min_price and not_min_price and not max_price and not not_max_price:
        products = products.filter(
            Q(bot_settings__min_price=0) | Q(bot_settings__min_price__isnull=True)
        )
    if not min_price and not not_min_price and max_price and not not_max_price:
        products = products.filter(bot_settings__max_price__gt=0)
    if not min_price and not not_min_price and not max_price and not_max_price:
        products = products.filter(Q(bot_settings__max_price=0) | Q(bot_settings__max_price__isnull=True))

    paginator = Paginator(products, 10)

    page_obj = paginator.get_page(page_number)

    published, archived = [0, 0]
    city_list = products.order_by(
        'bot_settings__city__name'
    ).values_list('bot_settings__city__name', 'bot_settings__city__id_in_kaspi').distinct()
    all_brands = ProductInIntegration.objects.order_by('product__brand').values_list('product__brand',
                                                                                     flat=True).distinct()
    context = {
        "integration": integration,
        "products_in_integration": page_obj,
        "published": published,
        "archived": archived,
        "city_ids": city_ids,
        "city_list": city_list,
        "all_brands": all_brands,
        "min_max_price": [min_price, not_min_price, max_price, not_max_price]
    }
    return render(request, 'core/products.html', context)


@login_required(login_url='/account/login/')
def update_product(request, product_id):
    active = request.GET.get("active", '')
    min_price = request.GET.get("min_price", 0)
    max_price = request.GET.get("max_price", 0)
    product = ProductInIntegration.objects.prefetch_related('bot_settings').get(pk=product_id)
    for bot_setting in product.bot_settings.all():
        if active:
            bot_setting.active = True if active == 'true' else False
            bot_setting.save()
        if min_price:
            bot_setting.min_price = int(min_price)
            bot_setting.save()
        if max_price:
            bot_setting.max_price = int(max_price)
            bot_setting.save()
    return JsonResponse({"success": True})


@login_required(login_url='/account/login/')
def update_bot_setting(request, bot_id):
    bot_setting = BotSetting.objects.get(pk=bot_id)
    min_price = request.GET.get("min_price", '')
    max_price = request.GET.get("max_price", '')
    step = request.GET.get("step", '')
    active = request.GET.get("active", '')
    if min_price != '':
        bot_setting.min_price = int(min_price)
        bot_setting.save()
        return JsonResponse({"success": True})
    elif max_price != '':
        bot_setting.max_price = int(max_price)
        bot_setting.save()
        return JsonResponse({"success": True})
    elif step != '':
        bot_setting.step = int(step)
        bot_setting.save()
        return JsonResponse({"success": True})
    elif active != '':
        bot_setting.active = True if active == 'true' else False
        bot_setting.save()
        return JsonResponse({"success": True})

core/templates/core/index.html
{% extends 'main.html' %}

{% block title %}Smart Manager{% endblock title %}

{% block content %}

    <div class="container" style="margin-top: 25px;">
        {% if perms.account.add_employee %}
            <h1>Парсеров (workers): <span>{{ active_workers_count }}</span></h1>
            <h1>Товаров в базе данных: <span>{{ products_count }}</span></h1>
            <br>
            <br>
            <br>
            <br>
            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th>Пользователь</th>
                        <th>Интеграции</th>
                        <th>Статус</th>
                    </tr>
                </thead>
                <tbody>
                    {% for employee in employee_list %}
                        <tr>
                            <td>{{ employee.user.email }}</td>
                            <td>
                                {% for integration in employee.company.first.integrations.all %}
                                    {{ integration.shop_name }}
                                    <br>
                                {% endfor %}
                            </td>
                            <td>
                                {% for integration in employee.company.first.integrations.all %}
                                    {% if integration.status %}
                                        Активный
                                    {% else %}
                                        Не активный
                                    {% endif %}
                                    <br>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h1>Добро пожаловать, {{ user.first_name }}</h1>
        {% endif %}
    </div>

{% endblock content %}

core/templates/core/integrations.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <div class="integrations">
        <div class="container">
            <div class="d-flex justify-content-between mb-3">
                <input type="text" id="myInputIntTable" onkeyup="searchInTable()" placeholder="начните вводить буквы...">
                {% if user.employee.company.first.integrations.all|length < 5 or perms.account.add_employee %}
                    <a href="{% url 'core:integration-add-view' %}" class="btn btn-outline-success btn-sm" role="button">Добавить</a>
                {% endif %}
            </div>
            <table class="table table-striped table-dark" id="integrationsTable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Интеграция</th>
                        <th>Статус</th>
                        <th>XML ссылка</th>
                        <th>Действия</th>
                        <th>Обновить список товаров</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for integration in user.employee.company.first.integrations.all %}
                        <tr>
                            <th>{{ integration.id }}</th>
                            <td>Каспи магазин {{ integration.shop_name }}</td>
                            <td id="status{{ integration.pk }}">
                                {% if integration.in_parsing_process %}
                                	Обработка товаров...
                                {% else %}
                                	{% if integration.status %}
                                        Активный
                                    {% else %}
                                        Не активный
                                    {% endif %}
                                {% endif %} 
                                
                            </td>
                            <td><a href="http://193.108.114.174/media/{{ integration.shop_name }}_{{ integration.partner_id }}.xml" onclick="copyURI(event)">Скопировать</a></td>
                            <td>{{ integration.last_update|date:"d.m.y H:i" }}</td>
                            <td>
                                {% if integration.admin_enabled %}
                                    <a onclick="alert('Даные обновляются! Подождите 30 минут.')" href="{% url 'core:integration-update-products' integration.id %}">
                                        <img src="{% static 'icons/circle-arrows.png' %}" width="20px;">
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                <a data-bs-toggle="modal" data-bs-target="#deleteAPIModal" onclick="setModal('Каспи магазин {{ integration.shop_name }}', '{% url 'core:integration-delete' integration.id %}')">
                                    <img src="{% static 'icons/trash.svg' %}" width="20px;">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <!-- Delete API Integration Modal -->
        <div class="modal fade" id="deleteAPIModal" tabindex="-1" aria-labelledby="deleteAPIModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="deleteAPIModalLabel">Подтвердите</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <h3>Будет удалена интеграция "<span id="modalIntegrationName"></span>"</h3>
                      </div>

                    <div class="modal-footer">
                        <a id="modalButton"><button type="button" class="btn btn-danger">Да</button></a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function searchInTable() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInputIntTable");
            filter = input.value.toUpperCase();
            table = document.getElementById("integrationsTable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
        function copyURI(evt) {
            evt.preventDefault();
            const encoded = encodeURI(evt.target.getAttribute('href'));
            navigator.clipboard.writeText(encoded).then(() => {
              /* clipboard successfully set */
                alert("Ссылка скопирована в буфер обмена!")
            }, () => {
              /* clipboard write failed */
                alert("Не удалось скопировать в буфер обмена!")
            });
        }
    </script>
    <script>
        function setModal(name, url) {
            document.getElementById("modalIntegrationName").innerText = name
            document.getElementById("modalButton").href = url
        }

        class Integration {
            constructor(id, status, adminEnabled, inParsingProcess) {
                this.id = id
                this.statusTd = document.getElementById(`status${this.id}`)
                this.status = status
                this.adminEnabled = adminEnabled
                this.inParsingProcess = inParsingProcess
                this.init()
            }

            init() {
                if (this.adminEnabled && !this.inParsingProcess) {
                    this.statusTd.style.cursor = "pointer"
                    this.statusTd.addEventListener('dblclick', ()=>{
                        this.change_status()
                        fetch(`${window.location.protocol}//${window.location.host}/integration/update/${this.id}?status=${this.status}`)
                    })
                }
            }

            change_status() {
                this.status = !this.status
                if (this.status) {
                    this.statusTd.innerText = 'Активный'
                } else {
                    this.statusTd.innerText = 'Не активный'
                }
            }
        }
        {% for integration in user.employee.company.first.integrations.all %}
            const integration{{ integration.pk }} = new Integration({{ integration.pk }}, {{ integration.status|lower }}, {{ integration.admin_enabled|lower }}, {{ integration.in_parsing_process|lower }})
        {% endfor %}
    </script>

{% endblock content %}

core/templates/core/staff.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <!-- Контент -->
    <div class="container">
        <div class="d-flex justify-content-between mb-3">
            <input type="text" id="myInput" onkeyup="searchInTable()" placeholder="Введите имя">
            <a href="{% url 'account:register-view' %}" class="btn btn-outline-success btn-sm" role="button">Добавить</a>
        </div>
        <table class="table table-striped table-dark" id="staffTable">
            <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Должность</th>
                <th>Создан</th>
                <th>Изменен</th>
                <th>Статус</th>
                <th>Действия</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for employee in user.employee.company.first.employees.all %}
                <tr>
                    <th>{{ employee.id }}</th>
                    <td>{{ employee.user.first_name }}</td>
                    <td>Директор</td>
                    <td>Дата</td>
                    <td>Дата</td>
                    <td>Действующий</td>
                    <td>Абсолютно ничего</td>
                    <td>
                        {% if not employee.user == user %}
                            <a data-bs-toggle="modal" data-bs-target="#deleteStaffModal">
                                <img src="{% static 'icons/trash.svg' %}" width="20px;">
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    <!-- Delete Staff Modal -->
    <div class="modal fade" id="deleteStaffModal" tabindex="-1" aria-labelledby="deleteStaffLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteStaffLabel">Подтвердите</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h3>Будет удален сотрудник "Имя"</h3>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger">Да</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        function searchInTable() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("staffTable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
{% endblock content %}