account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path("register/", views.register_view, name="register-view"),
    path("login/", views.login_view, name="login-view"),
    path("logout/", views.logout_view, name="logout-view"),
    path("profile/", views.profile_view, name="profile-view"),
]

core/urls.py
from django.views.generic import TemplateView
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path("", views.index_view, name="index-view"),
    path("integration/", views.integration_view, name="integration-view"),
    path("integration/add", views.integration_add_view, name="integration-add-view"),
    path("integration/update/<int:integration_id>", views.integration_update, name="integration-update"),
    path("integration/delete/<int:integration_id>", views.integration_delete, name="integration-delete"),
    path(
        "integration/update_products/<int:integration_id>",
        views.integration_update_products,
        name="integration-update-products"
    ),
    path("integration/export/<int:integration_id>", views.export_to_file, name="export_to_file"),
    path("integration/import/<int:integration_id>", views.import_from_file, name="import_from_file"),
    path("product/update/<int:product_id>", views.update_product, name="update-product"),
    path("products/", views.products_view, name="products-view"),
    path("products/<int:integration_id>", views.products_view, name="integration-products-view"),
    path("bot_setting/update/<int:bot_id>", views.update_bot_setting, name="update-bot-setting"),
    path("bot_setting/update-all/", views.update_all_bot_setting, name="update-all-bot-setting"),
    path("staff/", views.staff_view, name="staff-view"),
    path("get_products_for_parsing/", views.get_products_for_parsing, name="get-products-for-parsing"),
    path("parse_from_client/", views.parse_from_client, name="parse-from-client"),
    path("parse_client/", TemplateView.as_view(template_name='core/parser.html'), name="parse-client"),
    path("save_bot_ip_address", views.save_bot_ip_address, name="save-bot-ip-address"),
]

kaspi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('', include('core.urls')),
    path('account/', include('account.urls')),
    path('secret_admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main.html
{% load static %}
<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
{#    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.6.0/dist/full.min.css" rel="stylesheet" type="text/css" />#}
{#    <script src="https://cdn.tailwindcss.com"></script>#}
    <title>{% block title %}Kaspi Bot Test{% endblock title %}</title>
    {% block header %}{% endblock header %}
</head>

<body style="background-color: black;">
<!-- ШАПКА -->
<div class="header">
    <div class="container">
        {% with request.resolver_match.url_name as url_name %}
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'index-view' %}active{% endif %}" aria-current="page" href="{% url 'core:index-view' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'integration-view' %}active{% endif %}" href="{% url 'core:integration-view' %}">Интеграция</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if url_name == 'products-view' %}active{% endif %}" href="{% url 'core:products-view' %}">Товары</a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link {% if url_name == 'staff-view' %}active{% endif %}" href="{% url 'core:staff-view' %}">Сотрудники</a>#}
{#                </li>#}
                <li class="nav-item dropdown">
                    <a class="nav-link {% if url_name == 'profile-view' %}active{% endif %} dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ user.first_name }}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'account:profile-view' %}">Мой профиль</a></li>
                        <li><a class="dropdown-item" href="{% url 'account:logout-view' %}">Выйти</a></li>
                    </ul>
                </li>
            </ul>
        {% endwith %}
    </div>
</div>

{% block content %}

{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>